const guide = [
  {
    "name": "скульптура",
    routes: [
      {
        "sign": "a",
        "name": "Намасте",
        "high": "",
        "notUseSideRocks": "",
        "grade": "6а",
        "startType": 0,
        "picture": "sculpture/02.JPG",
      },
      {
        "sign": "b",
        "name": "Double Shelf",
        "high": true,
        "notUseSideRocks": "",
        "grade": "6c+",
        "startType": 0,
        "picture": "sculpture/02.JPG",
      },
      {
        "sign": "c",
        "name": "Джедай",
        "high": "",
        "notUseSideRocks": "",
        "grade": "6a",
        "startType": 0,
        "picture": "sculpture/01.JPG",
      },
      {
        "sign": "d.1",
        "name": "11 січня",
        "high": "",
        "notUseSideRocks": "",
        "grade": "6c",
        "startType": 0,
        "picture": "sculpture/01.JPG"
      },
      {
        "sign": "d.2",
        "name": "11 січня",
        "high": "",
        "notUseSideRocks": "",
        "grade": "6c",
        "startType": 0,
        "picture": "sculpture/01.JPG",
      },
      {
        "sign": "e",
        "name": "Острів Пасхи",
        "high": "",
        "notUseSideRocks": "",
        "grade": 5,
        "startType": 0,
        "picture": "sculpture/01.JPG",
      },
      {
        "sign": "f",
        "name": "Зірка Смерті",
        "high": "",
        "notUseSideRocks": "",
        "grade": "7c",
        "startType": 1,
        "picture": "sculpture/06.JPG",
      },
      {
        "sign": "g",
        "name": "Сокіл",
        "high": "",
        "notUseSideRocks": "",
        "grade": "6a+",
        "startType": 0,
        "picture": "sculpture/04.JPG",
      },
      {
        "sign": "h",
        "name": "Юнлінг",
        "high": "",
        "notUseSideRocks": "",
        "grade": 5,
        "startType": 1,
        "picture": "sculpture/03.JPG",
      },
      {
        "sign": "i",
        "name": "Падаван",
        "high": "",
        "notUseSideRocks": "",
        "grade": "6b+",
        "startType": 0,
        "picture": "sculpture/07.JPG",
      },
      {
        "sign": "j.1",
        "name": "маяй",
        "high": "",
        "notUseSideRocks": true,
        "grade": "project",
        "startType": 1,
        "picture": "sculpture/05.JPG",
      },
      {
        "sign": "j.2",
        "name": "маяй",
        "high": "",
        "notUseSideRocks": "",
        "grade": "6a+",
        "startType": 1,
        "picture": "sculpture/05.JPG",
      },
      {
        "sign": "k1",
        "name": "Nothing is impossible",
        "high": "-",
        "notUseSideRocks": true,
        "grade": "7b",
        "startType": 1,
        "picture": "sculpture/05.JPG",
      },
      {
        "sign": "k2",
        "name": "Nothing is impossible",
        "high": "",
        "notUseSideRocks": true,
        "grade": "project",
        "startType": 0,
        "picture": "sculpture/05.JPG",
      },
      {
        "sign": "l",
        "name": "ацтек",
        "high": "",
        "notUseSideRocks": "",
        "grade": "project",
        "startType": 1,
        "picture": "sculpture/05.JPG",
      },
      {
        "sign": "m",
        "name": "Рапануи",
        "high": "",
        "notUseSideRocks": "",
        "grade": "project",
        "startType": 0,
        "picture": "sculpture/05.JPG",
      },
      {
        "sign": "n",
        "name": "",
        "high": "",
        "notUseSideRocks": "",
        "grade": "project",
        "startType": 0,
        "picture": "sculpture/07.JPG",
      },
      {
        "sign": "o",
        "name": "",
        "high": "",
        "notUseSideRocks": "",
        "grade": "project",
        "startType": 0,
        "picture": "sculpture/07.JPG",
      },
    ]
  },
  {
    "name": "Восьминіг",
    routes: [
      {
        "sign": "a",
        "name": "Пес",
        "high": "",
        "notUseSideRocks": "",
        "grade": "6b",
      "startType": 1},
      {
        "sign": "b",
        "name": "Кіт",
        "high": "",
        "notUseSideRocks": "",
        "grade": "6b+",
      "startType": 2},
      {
        "sign": "c",
        "name": "Весільний Вантус",
        "high": "",
        "notUseSideRocks": "",
        "grade": "project",
      "startType": 0},
      {
        "sign": "d",
        "name": "Восьминіг",
        "high": true,
        "notUseSideRocks": "",
        "grade": "7с+",
      "startType": 0},
      {
        "sign": "e",
        "name": "Омана",
        "high": "",
        "notUseSideRocks": "",
        "grade": "6c",
      "startType": 0},
      {
        "sign": "f",
        "name": "Stone",
        "high": "",
        "notUseSideRocks": "",
        "grade": "6b",
      "startType": 0},
      {
        "sign": "g",
        "name": "Діамантова нога",
        "high": true,
        "notUseSideRocks": "",
        "grade": "7а",
      "startType": 0},
      {
        "sign": "h",
        "name": "Титанік",
        "high": true,
        "notUseSideRocks": "",
        "grade": "",                               
      "startType": 0},
      {
        "sign": "i",
        "name": "",
        "high": "",
        "notUseSideRocks": "",
        "grade": "",                               
      "startType": 0},
      {
        "sign": "j",
        "name": "",
        "high": "",
        "notUseSideRocks": "",
        "grade": "",                               
      "startType": 0},
      {
        "sign": "k",
        "name": "",
        "high": "",
        "notUseSideRocks": "",
        "grade": "",                               
      "startType": 0},
      {
        "sign": "l",
        "name": "сонячний",
        "high": "",
        "notUseSideRocks": "",
        "grade": "",                               
      "startType": 0},
    ]
  },
  {
    "name": "Чужий",
    routes: [
    {
      "sign": "a",
      "name": "Yamakasi",
      "high": "",
      "notUseSideRocks": "",
      "grade": 5,
    "startType": 0},
    {
      "sign": "b.1",
      "name": "Mike Jackson",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7а",
    "startType": 0},
    {
      "sign": "b.2",
      "name": "Mike Jackson",
      "high": "",
      "notUseSideRocks": "",
      "grade": 5,
    "startType": 0},
    {
      "sign": "c",
      "name": "Флоундер",
      "high": "",
      "notUseSideRocks": "",
      "grade": 5,
    "startType": 0},
    {
      "sign": "d",
      "name": "Міккі",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "e",
      "name": "Сєрий",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b+",
    "startType": 0},
    {
      "sign": "f",
      "name": "Чужий",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6c",
    "startType": 0},
    {
      "sign": "g",
      "name": "Тоторо",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "h",
      "name": "Квантовий Стрибок",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6c+",
    "startType": 0},
    {
      "sign": "i",
      "name": "Вухо Ван Гога",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7a",
    "startType": 0},
    {
      "sign": "j",
      "name": "Я маю право",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7а",
    "startType": 0},
    {
      "sign": "k.1",
      "name": "Язичник",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7b+",
    "startType": 0},
    {
      "sign": "k.2",
      "name": "Язичник",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7a",
    "startType": 0},
    {
      "sign": "l",
      "name": "Mask",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6a",
    "startType": 0},
    {
      "sign": "m",
      "name": "Дід і баба",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b",
    "startType": 0},
    {
      "sign": "n",
      "name": "Ламбарт",
      "high": "",
      "notUseSideRocks": "",
      "grade": 5,
    "startType": 0},
    {
      "sign": "o",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",                               
    "startType": 0},
    {
      "sign": "p",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",                               
    "startType": 0},
    ]
  },
  {
    "name": "кобра",
    routes: [
    {
      "sign": "a",
      "name": "Кобра",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7a",
    "startType": 0},
    {
      "sign": "b",
      "name": "t-rex",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b+",
    "startType": 0},
    {
      "sign": "c",
      "name": "Old Spice",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6a+",
    "startType": 0},
    {
      "sign": "d",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    ]
  },
  {
    "name": "Мікрорайон",
    routes: [
    {
      "sign": "a",
      "name": "Шовковий шлях",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6а",
    "startType": 0},
    {
      "sign": "b",
      "name": "Оптична Ілюзія",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6a",
    "startType": 0},
    {
      "sign": "c",
      "name": "Бубка боб",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7a",
    "startType": 2},
    {
      "sign": "d",
      "name": "Trash Metal",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6c+",
    "startType": 0},
    {
      "sign": "e",
      "name": "Стрийський",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "f.1",
      "name": "Момонтєнок",
      "high": "",
      "notUseSideRocks": "",
      "grade": 5,
    "startType": 0},
    {
      "sign": "f.2",
      "name": "Момонтєнок",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b",
    "startType": 0},
    {
      "sign": "g",
      "name": "5а",
      "high": "",
      "notUseSideRocks": "",
      "grade": 5,
    "startType": 0},
    {
      "sign": "h",
      "name": "Василіск",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b+",
    "startType": 0},
    {
      "sign": "i.1",
      "name": "China town",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "i.2",
      "name": "China town",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    ]
},
  {
    "name": "високий",
    routes: [
    {
      "sign": "a",
      "name": "К2",
      "high": true,
      "notUseSideRocks": "",
      "grade": "7b",
    "startType": 0},
    {
      "sign": "b",
      "name": "Сталеві яйця",
      "high": true,
      "notUseSideRocks": "",
      "grade": "6b",
    "startType": 0},
    {
      "sign": "c",
      "name": "Система нервів",
      "high": true,
      "notUseSideRocks": "",
      "grade": "6a+",
    "startType": 0},
    {
      "sign": "d",
      "name": "Гірка",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b",
    "startType": 0},
    {
      "sign": "e",
      "name": "Беспощадне стерво",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6c",
    "startType": 0},
    {
      "sign": "f",
      "name": "TGK",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "g",
      "name": "Кінець Вічності",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7а",
    "startType": 0},
    {
      "sign": "h",
      "name": "LSD",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    ]
},
  {
    "name": "Акваріум",
    routes: [
    {
      "sign": "a",
      "name": "Водний світ",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6c",
    "startType": 0},
    {
      "sign": "b",
      "name": "Гвинт",
      "high": "",
      "notUseSideRocks": "",
      "grade": 5,
    "startType": 0},
    {
      "sign": "c",
      "name": "Водоспад",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7a",
    "startType": 0},
    {
      "sign": "d",
      "name": "Морське чудовище",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7a+",
    "startType": 0},
    {
      "sign": "e",
      "name": "Moby dick",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6c",
    "startType": 0},
    {
      "sign": "f",
      "name": "Психи в городе",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6a",
    "startType": 0},
    {
      "sign": "g",
      "name": "Ever green",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6c",
    "startType": 0},
    {
      "sign": "h",
      "name": "Хто як хоче",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6c",
    "startType": 0},
    {
      "sign": "i",
      "name": "Жабка",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b",
    "startType": 0},
    {
      "sign": "j",
      "name": "Культурний гопнік",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b+",
    "startType": 0},
    {
      "sign": "k",
      "name": "Метод Хрюші",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7b",
    "startType": 0},
    {
      "sign": "l.1",
      "name": "Sven",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b",
    "startType": 0},
    {
      "sign": "l.2",
      "name": "Sven",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6a",
    "startType": 0},
    {
      "sign": "M",
      "name": "Три дні в берлозі",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b+",
    "startType": 0},
    {
      "sign": "N",
      "name": "Поцілунок Валькірії",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b",
    "startType": 0},
    {
      "sign": "O",
      "name": "Несси",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7a",
    "startType": 0},
    {
      "sign": "P",
      "name": "Jellyfish",
      "high": true,
      "notUseSideRocks": "",
      "grade": "7a",
    "startType": 0},
    {
      "sign": "Q1",
      "name": "какондра",
      "high": "",
      "notUseSideRocks": true,
      "grade": "project",
    "startType": 0},
    {
      "sign": "Q2",
      "name": "какондра",
      "high": "",
      "notUseSideRocks": true,
      "grade": "project",
    "startType": 0},
    {
      "sign": "R",
      "name": "ящірка",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6c",
    "startType": 0},
    {
      "sign": "s",
      "name": "експресо",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7a",
    "startType": 0},
    {
      "sign": "t",
      "name": "б12",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "u",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "v",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",                               
    "startType": 0},
    {
      "sign": "w",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",                               
    "startType": 0},
    ]
  },
  {
    "name": "Свиноматка",
    routes: [
    {
      "sign": "a",
      "name": "Акула",
      "high": true,
      "notUseSideRocks": "",
      "grade": "7а",
    "startType": 0},
    {
      "sign": "b",
      "name": "Скульптура Давида",
      "high": true,
      "notUseSideRocks": "",
      "grade": "7a+",
    "startType": 0},
    {
      "sign": "c",
      "name": "New Baseline",
      "high": true,
      "notUseSideRocks": "",
      "grade": "6b",
    "startType": 0},
    {
      "sign": "d",
      "name": "Креветко",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6a+",
    "startType": 0},
    {
      "sign": "e",
      "name": "Марія Хуанета",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6a+",
    "startType": 0},
    {
      "sign": "f.1",
      "name": "Дон Хуан",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6a",
    "startType": 0},
    {
      "sign": "f.2",
      "name": "Дон Хуан",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "g",
      "name": "Перші кроки",
      "high": "",
      "notUseSideRocks": "",
      "grade": 5,
    "startType": 0},
    {
      "sign": "h",
      "name": "Smile",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6с+",
    "startType": 0},
    {
      "sign": "i.1",
      "name": "Бойовий дух",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "i.2",
      "name": "Бойовий дух",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7b",
    "startType": 0},
    {
      "sign": "j",
      "name": "Пенсійний",
      "high": "",
      "notUseSideRocks": "",
      "grade": 5,
    "startType": 0},
    {
      "sign": "k",
      "name": "Хрящик",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6a",
    "startType": 0},
    {
      "sign": "l",
      "name": "Коала",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7a+",
    "startType": 0},
    {
      "sign": "m",
      "name": "Морена",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6a",
    "startType": 0},
    ]
},
  {
    "name": "Пиріжок",
    routes: [
    {
      "sign": "a",
      "name": "Пиріжок",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b",
    "startType": 0},
    {
      "sign": "b",
      "name": "Процес Травлення",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6c",
    "startType": 0},
    {
      "sign": "c",
      "name": "Морська зірка",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6c+",
    "startType": 0},
    {
      "sign": "d",
      "name": "Трон",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b",
    "startType": 0},
    {
      "sign": "e",
      "name": "Троя",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6а",
    "startType": 0},
    {
      "sign": "f",
      "name": "I`m Ent",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7a",
    "startType": 2},
    {
      "sign": "g",
      "name": "Буки",
      "high": true,
      "notUseSideRocks": "",
      "grade": "7a+",
    "startType": 2},
    {
      "sign": "h",
      "name": "ФМТ",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6a+",
    "startType": 0},
    {
      "sign": "i",
      "name": "Верхом на звезде",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b",
    "startType": 0},
    {
      "sign": "j",
      "name": "Скат",
      "high": "",
      "notUseSideRocks": "",
      "grade": 5,
    "startType": 0},
    {
      "sign": "k",
      "name": "шипіт",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b",
    "startType": 0},
    {
      "sign": "l",
      "name": "хлоп хлоп",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b",
    "startType": 0},
    {
      "sign": "m",
      "name": "rebirth",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7a",
    "startType": 0},
    {
      "sign": "n",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",                               
    "startType": 0},
    {
      "sign": "o",
      "name": "Nu",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",                               
    "startType": 0},
    ]
  },
  {
    "name": "Ларі",
    routes: [
    {
      "sign": "a",
      "name": "Місячне сяйво твого тіла",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6a",
    "startType": 0},
    {
      "sign": "b",
      "name": "Школа пацана",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "c",
      "name": "Ларі",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6c+",
    "startType": 0},
    {
      "sign": "d",
      "name": "Інвалід",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6a",
    "startType": 0},
    {
      "sign": "e",
      "name": "Точка 23",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b",
    "startType": 0},
    {
      "sign": "f",
      "name": "Take a look around",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7a+",
    "startType": 0},
    {
      "sign": "g",
      "name": "Noname",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b",
    "startType": 2},
    {
      "sign": "h",
      "name": "Next level",
      "high": true,
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "i",
      "name": "dnb",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6а",
    "startType": 0},
    {
      "sign": "j",
      "name": "Робінзон павло",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b",
    "startType": 0},
    ]
  },
  {
    "name": "Острів",
    routes: [
    {
      "sign": "a",
      "name": "такоє",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6a",
    "startType": 0},
    {
      "sign": "b",
      "name": "Атлас...",
      "high": true,
      "notUseSideRocks": "",
      "grade": "6b",
    "startType": 0},
    {
      "sign": "e",
      "name": "Острів",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6с",
    "startType": 0},
    {
      "sign": "c",
      "name": "Омерта",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7a",
    "startType": 0},
    {
      "sign": "d",
      "name": "Широ",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6a+",
    "startType": 0},
    {
      "sign": "f",
      "name": "сякое",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    ]
  },
  {
    "name": "Сан Франциско",
    routes: [
    {
      "sign": "c",
      "name": "TriPoint",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b",
    "startType": 0},
    {
      "sign": "b",
      "name": "Sex in City",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6c",
    "startType": 0},
    {
      "sign": "c",
      "name": "Bye bye bitch",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b",
    "startType": 0},
    {
      "sign": "d",
      "name": "pad",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6а",
    "startType": 0},
    {
      "sign": "e",
      "name": "Golden Gate",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "f",
      "name": "Alcatraz",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b+",
    "startType": 0},
    {
      "sign": "g",
      "name": "Coit Tower",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6c+",
    "startType": 0},
    {
      "sign": "h.1",
      "name": "harves moon",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "h.2",
      "name": "harves moon",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7b+",
    "startType": 0},
    ]
  },
  {
    "name": "Пять",
    routes: [
    {
      "sign": "a",
      "name": "як книжка пище",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6a+",
    "startType": 0},
    {
      "sign": "b.1",
      "name": "Серпом по яйцях",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "b.2",
      "name": "Серпом по яйцях",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7c",
    "startType": 0},
    {
      "sign": "c",
      "name": "Кросовок",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6a",
    "startType": 0},
    {
      "sign": "d",
      "name": "Асікси",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6a+",
    "startType": 0},
    {
      "sign": "e",
      "name": "Попугай",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "f1",
      "name": "Пять",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7с",
    "startType": 0},
    {
      "sign": "f2",
      "name": "Пять",
      "high": "",
      "notUseSideRocks": "",
      "grade": "8а",
    "startType": 0},
    {
      "sign": "g",
      "name": "Лошадь Губернатора",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6a",
    "startType": 0},
    {
      "sign": "h",
      "name": "freek",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    ]
  },
  {
    "name": "Слон",
    routes: [
    {
      "sign": "a",
      "name": "Мавка лісова",
      "high": "",
      "notUseSideRocks": "",
      "grade": 5,
    "startType": 0},
    {
      "sign": "b",
      "name": "Джаз",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "c",
      "name": "Гніздо на голові Слона",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7а",
    "startType": 0},
    {
      "sign": "d",
      "name": "Соня лісова",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6a",
    "startType": 0},
    {
      "sign": "e",
      "name": "Серце",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b",
    "startType": 0},
    ]
  },
  {
    "name": "bishop",
    routes: [
    {
      "sign": "а",
      "name": "bishop I",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6с",
    "startType": 0},
    {
      "sign": "b",
      "name": "bishop II",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6с",
    "startType": 0},
    {
      "sign": "c",
      "name": "motor way",
      "high": true,
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "d",
      "name": "Ребро Ван Дама",
      "high": true,
      "notUseSideRocks": "",
      "grade": "7а",
    "startType": 0},
    {
      "sign": "e",
      "name": "Вкрадена Марія",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6а",
    "startType": 0},
    {
      "sign": "f",
      "name": "Вечірній Стрий",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6a",
    "startType": 0},
    ]
  },
  {
    "name": "Paradise",
    routes: [
    {
      "sign": "a",
      "name": "Апостол Петро",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "b",
      "name": "покер",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b+",
    "startType": 0},
    {
      "sign": "c",
      "name": "вкрадене щастя",
      "high": "-лівий",
      "notUseSideRocks": "",
      "grade": "7a+",
    "startType": 0},
    {
      "sign": "d",
      "name": "ямайка",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6а",
    "startType": 0},
    {
      "sign": "e",
      "name": "dragon fly",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "f",
      "name": "Artists conk",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "g",
      "name": "харківський",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7a",
    "startType": 0},
    {
      "sign": "h",
      "name": "чорна змія",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7a",
    "startType": 0},
    {
      "sign": "i",
      "name": "вечірній поліспаст",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b+",
    "startType": 0},
    {
      "sign": "k",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",                               
    "startType": 0},
    {
      "sign": "l",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",                               
    "startType": 0},
    {
      "sign": "m",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",
    "startType": 0},
    {
      "sign": "n",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",
    "startType": 0},
    ]
  },
  {
    "name": "underworld",
    routes: [
    {
      "sign": "a",
      "name": "бобо",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6а",
    "startType": 0},
    {
      "sign": "b",
      "name": "deep blue",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7а",
    "startType": 0},
    {
      "sign": "c",
      "name": "gold rose",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7а",
    "startType": 0},
    {
      "sign": "d",
      "name": "space gray",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6с+",
    "startType": 0},
    {
      "sign": "e",
      "name": "чудо",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7b",
    "startType": 0},
    {
      "sign": "f",
      "name": "юдо",
      "high": "",
      "notUseSideRocks": true,
      "grade": "project",
    "startType": 0},
    {
      "sign": "g",
      "name": "dreamcatcher",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b",
    "startType": 0},
    {
      "sign": "h",
      "name": "tnt",
      "high": "",
      "notUseSideRocks": true,
      "grade": "project",
    "startType": 0},
    {
      "sign": "i",
      "name": "млинець",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6c+",
    "startType": 0},
    {
      "sign": "j",
      "name": "requiem",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7b",
    "startType": 0},
    {
      "sign": "k",
      "name": "space cake",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "l",
      "name": "futurama",
      "high": "",
      "notUseSideRocks": true,
      "grade": "project",
    "startType": 0},
    {
      "sign": "m",
      "name": "космічний лось",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "n",
      "name": "карнавал",
      "high": "",
      "notUseSideRocks": true,
      "grade": "project",
    "startType": 0},
    {
      "sign": "o",
      "name": "хочу в бло",
      "high": "",
      "notUseSideRocks": true,
      "grade": "6c+",
    "startType": 0},
    {
      "sign": "p",
      "name": "цікавий",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6a",
    "startType": 0},
    {
      "sign": "q.1",
      "name": "Walking stoned",
      "high": "",
      "notUseSideRocks": "",
      "grade": "prj",
    "startType": 0},
    {
      "sign": "q.2",
      "name": "Walking stoned",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7a+",
    "startType": 0},
    {
      "sign": "r",
      "name": "чорний",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b",
    "startType": 0},
    {
      "sign": "s",
      "name": "панда",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6a",
    "startType": 0},
    {
      "sign": "t",
      "name": "зелений павук",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b+",
    "startType": 0},
    {
      "sign": "u",
      "name": "доремідо",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6c",
    "startType": 0},
    {
      "sign": "v",
      "name": "глечики",
      "high": "",
      "notUseSideRocks": "",
      "grade": "7a",
    "startType": 0},
    {
      "sign": "w",
      "name": "underworld",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6b",
    "startType": 0},
    {
      "sign": "x",
      "name": "Black Hole",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "y",
      "name": "Brown dwarfs",
      "high": "",
      "notUseSideRocks": "",
      "grade": "Project",
    "startType": 0},
    {
      "sign": "z",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",
    "startType": 0},
    ]
  },
  {
    "name": "Космос",
    routes: [
    {
      "sign": "a.1",
      "name": "Розуелл 47",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "a.1",
      "name": "Розуелл 47",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "b",
      "name": "сомбреро",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "c",
      "name": "молочний шлях",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6с",
    "startType": 0},
    {
      "sign": "d",
      "name": "андромеда",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "e",
      "name": "вир",
      "high": "",
      "notUseSideRocks": "",
      "grade": "6с",
    "startType": 0},
    {
      "sign": "f",
      "name": "магеланова хмара",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "g",
      "name": "трикутник",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "h",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",
    "startType": 0},
    {
      "sign": "i",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",
    "startType": 0},
    {
      "sign": "k",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",
    "startType": 0},
    {
      "sign": "l",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",
    "startType": 0},
    {
      "sign": "m.1",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",
    "startType": 0},
    {
      "sign": "m.2",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",
    "startType": 0},
    {
      "sign": "o",
      "name": "Міжгалактична любов",
      "high": "",
      "notUseSideRocks": "",
      "grade": "project",
    "startType": 0},
    {
      "sign": "p",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",
    "startType": 0},
    {
      "sign": "q",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",
    "startType": 0},
    ]
  },
  {
    "name": "Далекий космос",
    routes: [
    {
      "sign": "a",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",
    "startType": 0},
    {
      "sign": "b",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",
    "startType": 0},
    {
      "sign": "c",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",
    "startType": 0},
    ]
  },
  
  {
    "name": "MagicWood",
    routes: [
    {
      "sign": "a",
      "name": "факел",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",
    "startType": 0},
    {
      "sign": "b.1",
      "name": "цунамі",
      "high": true,
      "notUseSideRocks": "",
      "grade": "",
    "startType": 0},
    {
      "sign": "b.2",
      "name": "цунамі",
      "high": true,
      "notUseSideRocks": "",
      "grade": "",
    "startType": 0},
    {
      "sign": "c",
      "name": "world cup",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",
    "startType": 0},
    {
      "sign": "d",
      "name": "світ підхватів",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",
    "startType": 0},
    {
      "sign": "e",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",
    "startType": 0},
    ]
  },
  {
    "name": "Печера",
    routes: [
    {
      "sign": "a",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",
    "startType": 0},
    {
      "sign": "b",
      "name": "",
      "high": "",
      "notUseSideRocks": "",
      "grade": "",
    "startType": 0}
    ]
  },
];
export default guide;